"""Guards against the BOM class of fault.

A UTF-8 BOM once appeared at the head of account_monitor.py. Streamlit's own
loader tolerates it, so the app looked fine, but _cascade.py reads that file
as text and runs ast.parse over it -- which raises on a BOM. The 同步账户
button therefore failed silently, and it took a manual hexdump to find.

Two independent guards, because either one alone can be worked around:
  1. no source file carries a BOM in the first place;
  2. every loader that reads a .py file as text tolerates one anyway.
"""

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).parents[1]
BOM = b"\xef\xbb\xbf"

SKIP_DIRS = {
    ".git", "__pycache__", ".pytest_cache", "venv", ".venv", "env",
    "node_modules", ".mypy_cache", "build", "dist", ".ruff_cache",
}


def python_files():
    for path in ROOT.rglob("*.py"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        yield path


def test_no_python_file_starts_with_a_bom():
    offenders = [
        str(path.relative_to(ROOT))
        for path in python_files()
        if path.read_bytes().startswith(BOM)
    ]
    assert offenders == [], (
        "UTF-8 BOM found at the head of: "
        + ", ".join(offenders)
        + ". Strip it (write the file without a BOM); ast.parse raises on it."
    )


# Lines that pull another module's *source* off disk. These must be BOM
# tolerant even though guard 1 should already keep BOMs out of the tree,
# because the file can be regenerated by an editor between checkouts.
FRAGILE_SOURCE_READ = re.compile(r'read_text\(\s*encoding\s*=\s*"utf-8"\s*\)')


def test_loaders_that_parse_python_source_tolerate_a_bom():
    """Only flag reads whose result is handed to ast.parse/compile.

    Reading source merely to assert substrings in it is unaffected by a BOM,
    so widening this check to every source read would produce noise rather
    than protection.
    """
    offenders = []
    for path in python_files():
        text = path.read_text(encoding="utf-8-sig")
        if "ast.parse(" not in text and "compile(" not in text:
            continue
        for lineno, line in enumerate(text.splitlines(), 1):
            if not FRAGILE_SOURCE_READ.search(line):
                continue
            if ".py" in line or "_SRC" in line:
                offenders.append(f"{path.relative_to(ROOT)}:{lineno}")
    assert offenders == [], (
        "these read Python source with encoding='utf-8'; use 'utf-8-sig' so a "
        "stray BOM cannot break ast.parse/compile: " + ", ".join(offenders)
    )


@pytest.mark.parametrize(
    "relative_path",
    [
        "_cascade.py",
        "_run_sync.py",
        "_run_price_refresh.py",
        "pages/1_📊_AI_估值评分.py",
        "pages/2_📈_期权分析.py",
    ],
)
def test_known_source_loaders_use_bom_tolerant_encoding(relative_path):
    """Named explicitly so a regression points straight at the failing loader."""
    text = (ROOT / relative_path).read_text(encoding="utf-8-sig")
    assert 'read_text(encoding="utf-8-sig")' in text
